"use client";

interface ResponsiveImageProps {
    /** Base name of the image (without extension), e.g., "camping" */
    baseName: string;
    /** Alt text for accessibility */
    alt: string;
    /** Additional CSS classes for the img element */
    className?: string;
    /** Whether to use fill mode (absolute positioning) */
    fill?: boolean;
    /** Loading strategy: "lazy" (default) or "eager" */
    loading?: "lazy" | "eager";
    /** Available widths in the optimized folder */
    sizes?: number[];
    /** Sizes attribute for responsive images */
    sizesAttr?: string;
}

/**
 * Responsive image component that serves WebP images with srcset
 * Uses images from /optimized/ folder generated by the optimization script
 */
export function ResponsiveImage({
    baseName,
    alt,
    className = "",
    fill = false,
    loading = "lazy",
    sizes = [640, 1024, 1920],
    sizesAttr = "(max-width: 640px) 640px, (max-width: 1024px) 1024px, 1920px",
}: ResponsiveImageProps) {
    // Build srcset for WebP
    const srcSet = sizes
        .map((width) => `/optimized/${baseName}-${width}w.webp ${width}w`)
        .join(", ");

    // Fallback to full-size WebP
    const src = `/optimized/${baseName}.webp`;

    const imgStyles = fill
        ? "absolute inset-0 w-full h-full"
        : "";

    return (
        <picture>
            <source
                type="image/webp"
                srcSet={srcSet}
                sizes={sizesAttr}
            />
            <img
                src={src}
                alt={alt}
                loading={loading}
                decoding="async"
                className={`${imgStyles} ${className}`.trim()}
            />
        </picture>
    );
}
